In [ ]:
# Necessary github Package:
!git clone https://github.com/matterport/Mask_RCNN.git

Cloning into 'Mask_RCNN'...
remote: Enumerating objects: 956, done.
remote: Total 956 (delta 0), reused 0 (delta 0), pack-reused 956
Receiving objects: 100% (956/956), 125.23 MiB | 23.31 MiB/s, done.
Resolving deltas: 100% (565/565), done.


In [ ]:
# install dependencies
!pip install tensorflow>=1.3.0 keras>=2.0.8 opencv-python h5py imgaug IPython

In [ ]:
# download weights
!wget https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5  /content/Mask_RCNN/samples/coco/

--2022-05-26 15:09:40--  https://github.com/matterport/Mask_RCNN/releases/download/v2.0/mask_rcnn_coco.h5
Resolving github.com (github.com)... 140.82.114.3
Connecting to github.com (github.com)|140.82.114.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://objects.githubusercontent.com/github-production-release-asset-2e65be/107595270/872d3234-d21f-11e7-9a51-7b4bc8075835?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20220526%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220526T150940Z&X-Amz-Expires=300&X-Amz-Signature=c75e652a659eab5970d8b0bd4b3438eb24043518e1e9d725f3fd4d4ca4d168bb&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=107595270&response-content-disposition=attachment%3B%20filename%3Dmask_rcnn_coco.h5&response-content-type=application%2Foctet-stream [following]
--2022-05-26 15:09:40--  https://objects.githubusercontent.com/github-production-release-asset-2e65be/107595270/872d3234-d21f-11e7-9a51-7b4bc8075835?X-

In [ ]:
# necessary imports
import os
import sys
import random
import math
import numpy as np
import skimage.io
import matplotlib
import matplotlib.pyplot as plt
from tqdm import tqdm
import cv2

In [ ]:
# install remaining requirments
!pip install -r /content/Mask_RCNN/requirements.txt
!pip install 'h5py==2.10.0' --force-reinstall
!pip install q keras==1.2.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 296 kB 27.1 MB/s 
     |████████████████████████████████| 154 kB 64.7 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.9 MB 29.2 MB/s 
     |████████████████████████████████| 15.7 MB 57.5 MB/s 
  Attempting uninstall: six
    Found existing installation: six 1.15.0
    Uninstalling six-1.15.0:
      Successfully uninstalled six-1.15.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.6
    Uninstalling numpy-1.21.6:
      Successfully uninstalled numpy-1.21.6
  Attempting uninstall: h5py
    Found existing installation: h5py 3.1.0
    Uninstalling h5py-3.1.0:
      Successfully uninstalled h5py-3.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the so

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 175 kB 35.7 MB/s 
     |████████████████████████████████| 2.8 MB 56.6 MB/s 
  Created wheel for keras: filename=Keras-1.2.2-py3-none-any.whl size=209601 sha256=a2348cc165a37a937acbf98e05ef85e8d9d95757c0f34a5d6af811430391cf2f
  Stored in directory: /root/.cache/pip/wheels/d1/32/23/2a1db3765ec19c91503843380a4f92b6530598949c661c5fa2
  Created wheel for theano: filename=Theano-1.0.5-py3-none-any.whl size=2668111 sha256=82f9cfa87a3a303c37edae58f9cb787d4950ef678b1b277e64775821e1dbe727
  Stored in directory: /root/.cache/pip/wheels/26/68/6f/745330367ce7822fe0cd863712858151f5723a0a5e322cc144
Successfully built keras theano
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
ERROR: pip's dependency resolver does not currently take into account all the packages tha

In [ ]:
# setup the model architecture
!cd /content/Mask_RCNN/
!python3 setup.py install

python3: can't open file 'setup.py': [Errno 2] No such file or directory


In [ ]:
# switch to tensorflow older version
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
cd /content/Mask_RCNN

/content/Mask_RCNN


In [ ]:
# load the model
 ## Root directory of the project
ROOT_DIR = os.path.abspath("./")

import warnings
warnings.filterwarnings("ignore")

 ## Import Mask RCNN
sys.path.append(ROOT_DIR)  # To find local version of the library
from mrcnn import utils
import mrcnn.model as modellib
from mrcnn import visualize
 ## Import COCO config 
sys.path.append(os.path.join(ROOT_DIR, "samples/coco/"))  # To find local version
import coco

%matplotlib inline

Using TensorFlow backend.


In [ ]:
# Directory to save logs and trained model
MODEL_DIR = os.path.join(ROOT_DIR, "logs")

# Local path to trained weights file
COCO_MODEL_PATH = os.path.join('', "samples/coco/mask_rcnn_coco.h5")

# Download COCO trained weights from Releases if needed
if not os.path.exists(COCO_MODEL_PATH):
    utils.download_trained_weights(COCO_MODEL_PATH)

# Directory of images to run detection on
IMAGE_DIR = os.path.join(ROOT_DIR, "images")

... done downloading pretrained model!


In [ ]:
class InferenceConfig(coco.CocoConfig):
    # Set batch size to 1 since we'll be running inference on
    # one image at a time. Batch size = GPU_COUNT * IMAGES_PER_GPU
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1

config = InferenceConfig()
config.display()


Configurations:
BACKBONE                       resnet101
BACKBONE_STRIDES               [4, 8, 16, 32, 64]
BATCH_SIZE                     1
BBOX_STD_DEV                   [0.1 0.1 0.2 0.2]
COMPUTE_BACKBONE_SHAPE         None
DETECTION_MAX_INSTANCES        100
DETECTION_MIN_CONFIDENCE       0.7
DETECTION_NMS_THRESHOLD        0.3
FPN_CLASSIF_FC_LAYERS_SIZE     1024
GPU_COUNT                      1
GRADIENT_CLIP_NORM             5.0
IMAGES_PER_GPU                 1
IMAGE_CHANNEL_COUNT            3
IMAGE_MAX_DIM                  1024
IMAGE_META_SIZE                93
IMAGE_MIN_DIM                  800
IMAGE_MIN_SCALE                0
IMAGE_RESIZE_MODE              square
IMAGE_SHAPE                    [1024 1024    3]
LEARNING_MOMENTUM              0.9
LEARNING_RATE                  0.001
LOSS_WEIGHTS                   {'rpn_class_loss': 1.0, 'rpn_bbox_loss': 1.0, 'mrcnn_class_loss': 1.0, 'mrcnn_bbox_loss': 1.0, 'mrcnn_mask_loss': 1.0}
MASK_POOL_SIZE                 14
MASK_SHAPE         

In [ ]:
# Create model object in inference mode.
model = modellib.MaskRCNN(mode="inference", model_dir='mask_rcnn_coco.hy', config=config)
# Load weights trained on MS-COCO
model.load_weights('samples/coco/mask_rcnn_coco.h5', by_name=True)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Instructions for updating:
box_ind is deprecated, use box_indices instead


Instructions for updating:
Use `tf.cast` instead.


In [ ]:
# COCO Class names
class_names = ['BG', 'person', 'bicycle', 'car', 'motorcycle', 'airplane',
               'bus', 'train', 'truck', 'boat', 'traffic light',
               'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird',
               'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear',
               'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie',
               'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
               'kite', 'baseball bat', 'baseball glove', 'skateboard',
               'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup',
               'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
               'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza',
               'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed',
               'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote',
               'keyboard', 'cell phone', 'microwave', 'oven', 'toaster',
               'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors',
               'teddy bear', 'hair drier', 'toothbrush']

In [ ]:
# define functions to overlay masks on original image
# define random colors
def random_colors(N):
 np.random.seed(1)
 colors = [tuple(255 * np.random.rand(3)) for _ in range(N)]
 return colors
#apply mask to image
def apply_mask(image, mask, color, alpha=0.5):
 
  for n, c in enumerate(color):
    image[:, :, n] = np.where(
    mask == 1,
    image[:, :, n] * (1 - alpha) + alpha * c,
    image[:, :, n]
  )
  return image

  #take the image and apply the mask, box, and Label
def display_instances(image, boxes, masks, ids, names, scores):
 
  n_instances = boxes.shape[0]
  colors = random_colors(n_instances)
  if not n_instances:
    print("NO INSTANCES TO DISPLAY")
  else:
    assert boxes.shape[0] == masks.shape[-1] == ids.shape[0]
  for i, color in enumerate(colors):
    if not np.any(boxes[i]):
      continue
    y1, x1, y2, x2 = boxes[i]
    label = names[ids[i]]
    score = scores[i] if scores is not None else None
    caption = '{} {:.2f}'.format(label, score) if score else label
    mask = masks[:, :, i]
    image = apply_mask(image, mask, color)
    image = cv2.rectangle(image, (x1, y1), (x2, y2), color, 2)
    image = cv2.putText(
    image, caption, (x1, y1), cv2.FONT_HERSHEY_COMPLEX, 0.7, color, 2
 )
  return image

In [ ]:
def process_video(video_path,output_path,verbose=True):
  # get the fps rate of the video:
  video= cv2.VideoCapture(video_path)

  framespersecond= int(video.get(cv2.CAP_PROP_FPS))
  if verbose:
    print("The total number of frames in this video is ", framespersecond)
  # get the size of the frame (weight, height)
  
  length = int(video.get(cv2.CAP_PROP_FRAME_COUNT))
  success,image = video.read()
  #h, w, c = image.shape
  width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
  height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))       
  size=(width,height)
  # define a list of object detected in the video
  detected=[]
  # loop over frames and predict content

  out_video = cv2.VideoWriter(output_path,cv2.VideoWriter_fourcc(*'MJPG'),framespersecond,size)
  pbar=tqdm(desc='while loop',total=length)
  while success:
    #cv2.imwrite("/content/Mask_RCNN/dance/frame%d.jpg" % count, image)     # save frame as JPEG file 
    # Run detection
    results = model.detect([image], verbose=1)
    r = results[0]
    output=display_instances(image, r['rois'], r['masks'], r['class_ids'], class_names, r['scores'])
    detected.append(r['class_ids'])
    out_video.write(image)
    pbar.update(1)
    success,image = video.read()
  out_video.release()
  if verbose:
    print("Output video is created at {}".format(output_path))
  return detected

In [ ]:
process_video('/content/4K Video of Highway Traffic! (online-video-cutter.com).mp4','/content/out.avi',verbose=True)

The total number of frames in this video is  29




while loop:   0%|          | 0/171 [00:00<?, ?it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  234.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  121.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   1%|          | 1/171 [00:00<01:30,  1.88it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  232.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  120.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   1%|          | 2/171 [00:01<01:23,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  224.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   2%|▏         | 3/171 [00:01<01:19,  2.12it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  225.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   2%|▏         | 4/171 [00:01<01:17,  2.16it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  222.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  117.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   3%|▎         | 5/171 [00:02<01:16,  2.18it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  229.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  117.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   4%|▎         | 6/171 [00:02<01:15,  2.19it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  236.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  119.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   4%|▍         | 7/171 [00:03<01:14,  2.19it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  238.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  127.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   5%|▍         | 8/171 [00:03<01:14,  2.17it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  231.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  120.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   5%|▌         | 9/171 [00:04<01:16,  2.12it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  232.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  118.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   6%|▌         | 10/171 [00:04<01:16,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  238.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  128.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   6%|▋         | 11/171 [00:05<01:16,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  135.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   7%|▋         | 12/171 [00:05<01:16,  2.07it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  136.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   8%|▊         | 13/171 [00:06<01:16,  2.06it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  244.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  138.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   8%|▊         | 14/171 [00:06<01:16,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  251.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  130.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   9%|▉         | 15/171 [00:07<01:15,  2.06it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  128.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:   9%|▉         | 16/171 [00:07<01:16,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  245.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  127.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  10%|▉         | 17/171 [00:08<01:15,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  240.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  117.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  11%|█         | 18/171 [00:08<01:13,  2.08it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  237.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  117.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  11%|█         | 19/171 [00:09<01:13,  2.06it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  242.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  123.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  12%|█▏        | 20/171 [00:09<01:12,  2.07it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  238.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  119.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  12%|█▏        | 21/171 [00:10<01:11,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  250.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  132.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  13%|█▎        | 22/171 [00:10<01:10,  2.12it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  232.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  13%|█▎        | 23/171 [00:10<01:09,  2.13it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  235.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  120.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  14%|█▍        | 24/171 [00:11<01:08,  2.14it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  132.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  15%|█▍        | 25/171 [00:11<01:08,  2.14it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  247.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  122.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  15%|█▌        | 26/171 [00:12<01:08,  2.12it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  233.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  126.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  16%|█▌        | 27/171 [00:12<01:07,  2.13it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  244.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  131.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  16%|█▋        | 28/171 [00:13<01:06,  2.15it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  251.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  144.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  17%|█▋        | 29/171 [00:13<01:06,  2.13it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    1.00000  max:  248.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  140.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  18%|█▊        | 30/171 [00:14<01:05,  2.14it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  246.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  137.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  18%|█▊        | 31/171 [00:14<01:05,  2.14it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  248.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  140.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  19%|█▊        | 32/171 [00:15<01:05,  2.13it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  248.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  136.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  19%|█▉        | 33/171 [00:15<01:05,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  145.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  20%|█▉        | 34/171 [00:16<01:05,  2.08it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  253.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  145.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  20%|██        | 35/171 [00:16<01:05,  2.07it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  253.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  133.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  21%|██        | 36/171 [00:17<01:05,  2.06it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  235.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  22%|██▏       | 37/171 [00:17<01:04,  2.06it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  224.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  22%|██▏       | 38/171 [00:18<01:04,  2.08it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  242.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  23%|██▎       | 39/171 [00:18<01:02,  2.11it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  230.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  23%|██▎       | 40/171 [00:19<01:02,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  24%|██▍       | 41/171 [00:19<01:01,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  228.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  25%|██▍       | 42/171 [00:19<01:01,  2.09it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  223.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  117.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  25%|██▌       | 43/171 [00:20<01:00,  2.12it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  225.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  117.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  26%|██▌       | 44/171 [00:20<00:59,  2.14it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  223.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  26%|██▋       | 45/171 [00:21<00:58,  2.15it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  224.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  27%|██▋       | 46/171 [00:21<00:57,  2.16it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  227.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  117.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  27%|██▋       | 47/171 [00:22<00:58,  2.13it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  223.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  28%|██▊       | 48/171 [00:22<00:57,  2.15it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  224.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  117.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  29%|██▊       | 49/171 [00:23<00:58,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  235.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  118.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  29%|██▉       | 50/171 [00:23<00:57,  2.11it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  226.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  119.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  30%|██▉       | 51/171 [00:24<00:56,  2.11it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  223.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  30%|███       | 52/171 [00:24<00:56,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  238.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  117.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  31%|███       | 53/171 [00:25<00:56,  2.08it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  239.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  114.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  32%|███▏      | 54/171 [00:25<00:56,  2.08it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  225.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  114.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  32%|███▏      | 55/171 [00:26<00:55,  2.07it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  232.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  118.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  33%|███▎      | 56/171 [00:26<00:55,  2.07it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  226.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  33%|███▎      | 57/171 [00:27<00:55,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  240.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  123.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  34%|███▍      | 58/171 [00:27<00:55,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  230.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  119.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  35%|███▍      | 59/171 [00:28<00:54,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  227.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  35%|███▌      | 60/171 [00:28<00:54,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  222.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  36%|███▌      | 61/171 [00:29<00:53,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  36%|███▋      | 62/171 [00:29<00:53,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  37%|███▋      | 63/171 [00:30<00:53,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  37%|███▋      | 64/171 [00:30<00:52,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  38%|███▊      | 65/171 [00:31<00:52,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  39%|███▊      | 66/171 [00:31<00:51,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  39%|███▉      | 67/171 [00:32<00:50,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  40%|███▉      | 68/171 [00:32<00:50,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  40%|████      | 69/171 [00:32<00:49,  2.06it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  253.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  130.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  41%|████      | 70/171 [00:33<00:49,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  244.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  132.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  42%|████▏     | 71/171 [00:33<00:49,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  236.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  42%|████▏     | 72/171 [00:34<00:47,  2.07it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  248.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  43%|████▎     | 73/171 [00:34<00:47,  2.08it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  235.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  43%|████▎     | 74/171 [00:35<00:46,  2.11it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  226.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  44%|████▍     | 75/171 [00:35<00:44,  2.14it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  44%|████▍     | 76/171 [00:36<00:44,  2.13it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  45%|████▌     | 77/171 [00:36<00:44,  2.13it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  46%|████▌     | 78/171 [00:37<00:43,  2.12it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  221.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  46%|████▌     | 79/171 [00:37<00:42,  2.14it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  231.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  47%|████▋     | 80/171 [00:38<00:42,  2.17it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  222.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  47%|████▋     | 81/171 [00:38<00:41,  2.16it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  227.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  115.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  48%|████▊     | 82/171 [00:39<00:41,  2.17it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  237.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  122.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  49%|████▊     | 83/171 [00:39<00:41,  2.14it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  251.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  127.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  49%|████▉     | 84/171 [00:40<00:41,  2.09it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  136.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  50%|████▉     | 85/171 [00:40<00:41,  2.08it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  140.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  50%|█████     | 86/171 [00:41<00:42,  1.99it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  129.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  51%|█████     | 87/171 [00:41<00:42,  1.98it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  250.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  128.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  51%|█████▏    | 88/171 [00:42<00:41,  2.00it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  248.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  128.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  52%|█████▏    | 89/171 [00:42<00:41,  2.00it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  244.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  125.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  53%|█████▎    | 90/171 [00:43<00:40,  2.01it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  245.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  123.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  53%|█████▎    | 91/171 [00:43<00:39,  2.01it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  246.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  129.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  54%|█████▍    | 92/171 [00:44<00:38,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  245.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  130.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  54%|█████▍    | 93/171 [00:44<00:37,  2.09it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  238.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  126.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  55%|█████▍    | 94/171 [00:44<00:36,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  241.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  127.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  56%|█████▌    | 95/171 [00:45<00:36,  2.10it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  243.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  130.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  56%|█████▌    | 96/171 [00:45<00:36,  2.07it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  249.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  138.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  57%|█████▋    | 97/171 [00:46<00:35,  2.06it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  244.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  132.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  57%|█████▋    | 98/171 [00:46<00:35,  2.08it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  246.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  127.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  58%|█████▊    | 99/171 [00:47<00:34,  2.07it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  244.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  130.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  58%|█████▊    | 100/171 [00:47<00:34,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  254.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  131.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  59%|█████▉    | 101/171 [00:48<00:34,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  253.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  132.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  60%|█████▉    | 102/171 [00:48<00:34,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  133.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  60%|██████    | 103/171 [00:49<00:33,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  135.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  61%|██████    | 104/171 [00:49<00:32,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  133.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  61%|██████▏   | 105/171 [00:50<00:32,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  137.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  62%|██████▏   | 106/171 [00:50<00:31,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  135.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  63%|██████▎   | 107/171 [00:51<00:31,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  129.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  63%|██████▎   | 108/171 [00:51<00:31,  2.00it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  129.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  64%|██████▎   | 109/171 [00:52<00:31,  1.99it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  243.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  126.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  64%|██████▍   | 110/171 [00:52<00:30,  1.99it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  250.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  125.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  65%|██████▍   | 111/171 [00:53<00:30,  1.99it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  247.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  131.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  65%|██████▌   | 112/171 [00:53<00:29,  1.99it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  231.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  121.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  66%|██████▌   | 113/171 [00:54<00:28,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  245.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  129.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  67%|██████▋   | 114/171 [00:54<00:27,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  236.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  125.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  67%|██████▋   | 115/171 [00:55<00:27,  2.06it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  243.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  130.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  68%|██████▊   | 116/171 [00:55<00:26,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  243.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  131.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  68%|██████▊   | 117/171 [00:56<00:26,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  242.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  131.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  69%|██████▉   | 118/171 [00:56<00:25,  2.05it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  245.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  129.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  70%|██████▉   | 119/171 [00:57<00:25,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  250.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  139.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  70%|███████   | 120/171 [00:57<00:25,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  239.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  128.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  71%|███████   | 121/171 [00:58<00:24,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  149.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  71%|███████▏  | 122/171 [00:58<00:24,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  146.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  72%|███████▏  | 123/171 [00:59<00:23,  2.04it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  145.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  73%|███████▎  | 124/171 [00:59<00:23,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  253.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  141.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  73%|███████▎  | 125/171 [01:00<00:22,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  144.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  74%|███████▎  | 126/171 [01:00<00:22,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  148.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  74%|███████▍  | 127/171 [01:01<00:21,  2.06it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  145.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  75%|███████▍  | 128/171 [01:01<00:21,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  148.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  75%|███████▌  | 129/171 [01:02<00:20,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  142.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  76%|███████▌  | 130/171 [01:02<00:20,  2.01it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  146.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  77%|███████▋  | 131/171 [01:03<00:19,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  145.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  77%|███████▋  | 132/171 [01:03<00:19,  2.00it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  141.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  78%|███████▊  | 133/171 [01:04<00:18,  2.00it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  142.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  78%|███████▊  | 134/171 [01:04<00:18,  1.99it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  148.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  79%|███████▉  | 135/171 [01:05<00:17,  2.00it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  148.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  80%|███████▉  | 136/171 [01:05<00:17,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  146.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  80%|████████  | 137/171 [01:06<00:16,  2.03it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  144.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  81%|████████  | 138/171 [01:06<00:16,  2.01it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  139.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  81%|████████▏ | 139/171 [01:07<00:15,  2.01it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  254.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  137.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  82%|████████▏ | 140/171 [01:07<00:15,  2.01it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  254.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  137.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  82%|████████▏ | 141/171 [01:08<00:14,  2.00it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  144.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  83%|████████▎ | 142/171 [01:08<00:14,  2.02it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  140.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  84%|████████▎ | 143/171 [01:09<00:13,  2.01it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  252.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  133.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  84%|████████▍ | 144/171 [01:09<00:13,  2.01it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  139.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  85%|████████▍ | 145/171 [01:10<00:13,  1.99it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  246.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  129.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  85%|████████▌ | 146/171 [01:10<00:12,  1.98it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  244.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  133.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  86%|████████▌ | 147/171 [01:11<00:12,  1.98it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  240.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  126.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  87%|████████▋ | 148/171 [01:11<00:11,  1.95it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  239.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  121.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  87%|████████▋ | 149/171 [01:12<00:11,  1.94it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  238.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  122.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  88%|████████▊ | 150/171 [01:12<00:10,  1.95it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  237.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  119.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  88%|████████▊ | 151/171 [01:13<00:10,  1.93it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  242.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  125.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  89%|████████▉ | 152/171 [01:13<00:09,  1.95it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  231.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  114.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  89%|████████▉ | 153/171 [01:14<00:09,  1.96it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  246.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  124.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  90%|█████████ | 154/171 [01:14<00:08,  1.95it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  244.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  120.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  91%|█████████ | 155/171 [01:15<00:08,  1.93it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  240.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  125.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  91%|█████████ | 156/171 [01:15<00:07,  1.95it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  240.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  121.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  92%|█████████▏| 157/171 [01:16<00:07,  1.96it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  240.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  121.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  92%|█████████▏| 158/171 [01:16<00:06,  1.97it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  231.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  119.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  93%|█████████▎| 159/171 [01:17<00:06,  1.98it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  237.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  121.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  94%|█████████▎| 160/171 [01:17<00:05,  1.96it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  244.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  126.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  94%|█████████▍| 161/171 [01:18<00:05,  1.96it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  233.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  116.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  95%|█████████▍| 162/171 [01:18<00:04,  1.97it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  239.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  119.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  95%|█████████▌| 163/171 [01:19<00:04,  1.96it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  230.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  118.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  96%|█████████▌| 164/171 [01:19<00:03,  1.94it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  245.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  124.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  96%|█████████▋| 165/171 [01:20<00:03,  1.97it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  142.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  97%|█████████▋| 166/171 [01:20<00:02,  1.99it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  148.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  98%|█████████▊| 167/171 [01:21<00:01,  2.01it/s]

Processing 1 images
image                    shape: (360, 640, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  142.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.35390  max:    1.29134  float32




while loop:  98%|█████████▊| 168/171 [01:21<00:01,  2.05it/s]

Output video is created at /content/out.avi


[array([8, 3, 8, 1, 3, 3], dtype=int32),
 array([3, 8, 1, 8, 3], dtype=int32),
 array([3, 8, 3, 3], dtype=int32),
 array([3, 8, 9], dtype=int32),
 array([3, 8, 3, 3], dtype=int32),
 array([8, 3, 9, 3, 1], dtype=int32),
 array([3, 8, 3, 1], dtype=int32),
 array([3, 8, 8, 1, 9, 9], dtype=int32),
 array([8, 5, 8, 1, 3, 3, 9, 3, 9], dtype=int32),
 array([ 5, 29,  8,  3,  3,  9,  1,  8], dtype=int32),
 array([3, 3, 9, 5, 8, 1], dtype=int32),
 array([3, 3, 5, 8, 8, 8, 9, 3, 1], dtype=int32),
 array([3, 3, 3, 8, 8, 5, 3, 1], dtype=int32),
 array([3, 3, 5, 3, 3, 8, 8, 3], dtype=int32),
 array([3, 5, 3, 3, 3, 8, 3], dtype=int32),
 array([3, 3, 5, 3, 3, 3, 9, 8, 3], dtype=int32),
 array([3, 3, 3, 3, 8, 9, 8, 9], dtype=int32),
 array([3, 3, 3, 3, 8, 9, 8], dtype=int32),
 array([3, 3, 3, 9, 8, 3, 8, 8], dtype=int32),
 array([3, 3, 3, 3, 8, 8, 8], dtype=int32),
 array([3, 3, 8, 8, 3], dtype=int32),
 array([3, 3, 3, 3, 8, 8], dtype=int32),
 array([3, 3, 3, 3, 8, 8], dtype=int32),
 array([3, 3, 3, 3,

In [ ]:
class_names[9]

'boat'

In [ ]:
video= cv2.VideoCapture('/content/4K Video of Highway Traffic! (online-video-cutter.com).mp4')

width = int(video.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(video.get(cv2.CAP_PROP_FRAME_HEIGHT))       
size=(width,height)
print(size)

(640, 360)
